# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-02 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('data', '0003_podcastupdateresult_podcast_url')]

    operations = [
        migrations.AlterField(
            model_name='podcastupdateresult',
            name='podcast_url',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        )
    ]
