# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-24 02:07
from __future__ import unicode_literals

from django.contrib.postgres.search import SearchVector, SearchVectorField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("podcasts", "0037_index_podcast_lastupdate")]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="search_vector",
            field=SearchVectorField(null=True),
        )
    ]
