# Generated by Django 2.2.6 on 2019-12-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0040_podcast_update_interval_factor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="flattr_url",
            field=models.URLField(
                blank=True, db_index=True, max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="license",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="flattr_url",
            field=models.URLField(
                blank=True, db_index=True, max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="group_member_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="hub",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="license",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="new_location",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="related_podcasts",
            field=models.ManyToManyField(
                blank=True,
                related_name="_podcast_related_podcasts_+",
                to="podcasts.Podcast",
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="twitter",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
