# Generated by Django 2.2.6 on 2019-12-30 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0041_auto_20191230_2319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="podcasts.PodcastGroup",
            ),
        ),
    ]
