# Generated by Django 2.2.6 on 2019-12-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0044_auto_20191230_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='episode_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='latest_episode_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='max_episode_order',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
