# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podcasts', '0037_index_podcast_lastupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeQueue',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MergeQueueEntry',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('podcast', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='podcasts.Podcast',
                )),
                ('queue', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='maintenance.MergeQueue',
                )),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
