# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_podcast_mergequeue_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergequeueentry',
            name='queue',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='entries',
                related_query_name='entry',
                to='maintenance.MergeQueue',
            ),
        ),
    ]
