# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_rename_mergetask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mergetaskentry',
            old_name='queue',
            new_name='task',
        ),
    ]
