# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 09:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergetask',
            name='groups',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
