DELETE FROM `sanitizing_rules`;
INSERT INTO `sanitizing_rules` VALUES (1,1,1,'feeds2\\.feedburner\\.com','feeds.feedburner.com',1,'Rewriting for feedburner should happen as \"feeds2.feedburner.com\" -> \"feeds.feedburner.com\"');
INSERT INTO `sanitizing_rules` VALUES (2,1,1,'(?P<unchanged>feedburner\\.com.+)\\?format=xml','\\g<unchanged>',2,'Feedburner URLs should have their \"?format=xml\" query string removed: \r\n\r\nhttp://feeds2.feedburner.com/linuxoutlaws?format=xml \r\nhttp://feeds.feedburner.com/linuxoutlaws \r\n');
INSERT INTO `sanitizing_rules` VALUES (3,1,1,'^\\s+','',0,'Remove leading whitespaces');
INSERT INTO `sanitizing_rules` VALUES (4,1,1,'\\s+$','',0,'Remove trailing whitespaces');
INSERT INTO `sanitizing_rules` VALUES (5,1,1,'^[^(https?):].+','',100,'Empty any string that doesn\'t start with either http or https');
INSERT INTO `sanitizing_rules` VALUES (7,1,0,'(?P<unchanged>feedburner\\.com.+)\\/$','\\g<unchanged>',2,'Feedburner URLs sometimes have a trailing slash, which can be removed safely');
INSERT INTO `sanitizing_rules` VALUES (8,1,1,'^.*[^\\x20-\\x7E].*$', '', 50, 'Remove URLs with non-ascii characters');
INSERT INTO `sanitizing_rules` VALUES (9,1,0,'^http://leoville\\.tv/podcasts/(?P<podcast>\\w+)\\.xml$', 'http://leo.am/podcasts/\\g<podcast>', 10, 'Rewrite URLs of TWiT Podcasts because most users use a URL that is going to break soon (bug 885)');
INSERT INTO `sanitizing_rules` VALUES (10,1,0,'^http://www\\.dancarlin\\.com/dchh\\.xml$', 'http://feeds.feedburner.com/dancarlin/history', 10, 'Rewrite podcast URL of Dan Carlin\'s Hardcore History because the old URL doesn\'t work anymore (bug 855)');
INSERT INTO `sanitizing_rules` VALUES (11,1,1,'^.*\\s.*$', '', 10, 'All URLs that contain spaces are considered invalid');
INSERT INTO `sanitizing_rules` VALUES (12,0,1,'http://media.libsyn.com/media/(?P<res>.*)$', 'http://traffic.libsyn.com/\\g<res>', 10, 'Update new URL for libsy Podcasts (Learn Japanese with Beb and Alex)');
INSERT INTO `sanitizing_rules` VALUES (13,1,0,'^http://site\\.abc\\.go\\.com/abc/xml/podcastRSS\\?(.*&)?feedPublishKey=(?P<key>\\d+)(&.*)?$', 'http://a.abc.com/abc/xml/podcastRSS?feedPublishKey=\\g<key>', 100, 'Merge URLs for ABC Podcasts (bug 977)');
INSERT INTO `sanitizing_rules` VALUES (14,1,1,'^(?P<protocol>[a-zA-Z])://[-_\\w]+(:[^@]+)?@(?P<rest>.+)$', '\\g<protocol>://\\g<rest>', 20, 'Remove HTTP-Authentication from URLs');
INSERT INTO `sanitizing_rules` VALUES (15,0,1,'^(?P<unchanged>http://rpod\\.ru/personal/.+\\.mp[34])\\?[0-9a-z]+$', '\\g<unchanged>', 100, '');
INSERT INTO `sanitizing_rules` VALUES (16,0,1,'^http://\\d+\\.media\\.collegehumor\\.com/(?P<unchanged>.+)$', 'http://1.media.collegehumor.com/\\g<unchanged>', 100, '');
INSERT INTO `sanitizing_rules` VALUES (17,1,0,'(?i)^http://feeds\.feedburner\.com/ShotOfJaq$', 'http://shotofjaq.org/feed/', 100, 'Merges Shot of Jaq feeds to the URL given on their Website');
INSERT INTO `sanitizing_rules` VALUES (18,1,0,'http://shotofjaq\.org/feed$', 'http://shotofjaq.org/feed/', 100, 'Add trailing slash to Shot of Jaq feed URL');
INSERT INTO `sanitizing_rules` VALUES (19,1,0,'(?i)^http://feeds\\.feedburner\\.com/ShotOfJaqOGG$', 'http://feeds.feedburner.com/ShotOfJaqOgg', 100, 'Unify all Feedburner URLs for the Shot of Jaq Ogg feed (seems it doesn\'t have an shotofjaq.org url)');
INSERT INTO `sanitizing_rules` VALUES (20,1,0,'(?i)^http://feeds\\.feedburner\\.com/TEDTalks_video$', 'http://feeds.feedburner.com/tedtalks_video', 100, 'Unify all TEDTalks podcasts');
INSERT INTO `sanitizing_rules` VALUES (21,1,0,'(?i)^http://feeds\\.feedburner\\.com/TEDTalks_audio$', 'http://feeds.feedburner.com/tedtalks_audio', 100, 'Unify all TEDTalks podcasts');
INSERT INTO `sanitizing_rules` VALUES (22,1,0,'(?i)^http://feeds\\.feedburner\\.com/TedtalksHD$', 'http://feeds.feedburner.com/tedtalkshd', 100, 'Unify all TEDTalks podcasts');
INSERT INTO `sanitizing_rules` VALUES (23,1,0,'(?i)^http://feeds\\.feedburner\\.com/mintcastpodcast$', 'http://www.mintcast.org/feed/podcast/', 100, 'Unify mintCast feeds (bug 1035');
INSERT INTO `sanitizing_rules` VALUES (24,1,0,'(?i)^http://www.mintcast.org/feed/$', 'http://www.mintcast.org/feed/podcast/', 100, 'Unify mintCast feeds (bug 1035');
INSERT INTO `sanitizing_rules` VALUES (25,1,0,'(?i)^http://feeds\\.feedburner\\.com/ziffdavis/crankygeekspodcast$', 'http://feeds.ziffdavis.com/ziffdavis/crankygeekspodcast', 100, 'Unify Cranky Geed Podcasts (MP3) (bug 1032');
INSERT INTO `sanitizing_rules` VALUES (26,1,0,'^http://rssnewsapps\\.ziffdavis\\.com/audioblogs/crankygeeks/cg\\.audio\\.xml/?$', 'http://feeds.ziffdavis.com/ziffdavis/crankygeekspodcast', 100, 'Unify Cranky Geed Podcasts (MP3) (bug 1032');
INSERT INTO `sanitizing_rules` VALUES (27,1,0,'^http://feeds\\.ziffdavis\\.com/ziffdavis/crankygeekspodcast/$', 'http://feeds.ziffdavis.com/ziffdavis/crankygeekspodcast', 100, 'Unify Cranky Geed Podcasts (MP3) (bug 1032');
INSERT INTO `sanitizing_rules` VALUES (28,1,0,'(?i)^http://feeds\\.feedburner\\.com/ziffdavis/cgh264video$', 'http://feeds.ziffdavis.com/ziffdavis/cgh264video', 100, 'Unify Cranky Geed Podcasts (H.264) (bug 1032');
INSERT INTO `sanitizing_rules` VALUES (29,1,0,'^http://rssnewsapps\\.ziffdavis\\.com/audioblogs/crankygeeks/cg\\.h\\.264\\.xml$', 'http://feeds.ziffdavis.com/ziffdavis/cgh264video', 100, 'Unify Cranky Geed Podcasts (H.264) (bug 1032');
INSERT INTO `sanitizing_rules` VALUES (30,1,0,'^http://rssnewsapps\\.ziffdavis\\.com/audioblogs/crankygeeks/cg\\.ipod\\.xml$', 'http://feeds.ziffdavis.com/ziffdavis/cgipodvideo', 100, 'Unify Cranky Geed Podcasts (iPod Video) (bug 1032');
INSERT INTO `sanitizing_rules` VALUES (31,1,0,'^http://rssnewsapps\\.ziffdavis\\.com/audioblogs/crankygeeks/cg\\.mp4\\.xml$', 'http://feeds.ziffdavis.com/ziffdavis/cgipodvideo', 100, 'Unify Cranky Geed Podcasts (iPod Video) (bug 1032');
INSERT INTO `sanitizing_rules` VALUES (32,1,0,'(?i)^http://feeds\\.feedburner\\.com/ziffdavis/cgipodvideo$', 'http://feeds.ziffdavis.com/ziffdavis/cgipodvideo', 100, 'Unify Cranky Geed Podcasts (iPod Video) (bug 1032');
INSERT INTO `sanitizing_rules` VALUES (33,1,0,'^http://feeds\\.ziffdavis\\.com/ziffdavis/cgmpeg4video/$', 'http://feeds.ziffdavis.com/ziffdavis/cgipodvideo', 100, 'Unify Cranky Geed Podcasts (iPod Video) (bug 1032');
INSERT INTO `sanitizing_rules` VALUES (34,1,0,'^http://feeds\\.ziffdavis\\.com/ziffdavis/cgipodvideo\\?format=xml$', 'http://feeds.ziffdavis.com/ziffdavis/cgipodvideo', 100, 'Unify Cranky Geed Podcasts (iPod Video) (bug 1032');
INSERT INTO `sanitizing_rules` VALUES (35,1,0,'^http://rssnewsapps\\.ziffdavis\\.com/audioblogs/crankygeeks/cg\\.wmv\\.xml$', 'http://feeds.feedburner.com/ziffdavis/cgwmvvideo', 100, 'Unify Cranky Geed Podcasts (WMV) (bug 1032');
INSERT INTO `sanitizing_rules` VALUES (36,1,0,'^http://noagenda\\.podshow\\.com/feed$', 'http://www.mevio.com/feeds/noagenda.xml', 100, 'Unify No Agend Feeds');
INSERT INTO `sanitizing_rules` VALUES (37,1,0,'^(?P<protocol>\\w+)://gdata\\.youtube\\.com/feeds/base/users/(?P<username>\\w+)/uploads\\?alt=rss.*$', '\\g<protocol>://www.youtube.com/rss/user/\g<username>/videos.rss', 100, 'Rewrite Youtube API Feeds to canonical URLs (bug 1057)');

