DELETE FROM `sanitizing_rules`;
INSERT INTO `sanitizing_rules` VALUES (1,1,1,'feeds2\\.feedburner\\.com','feeds.feedburner.com',1,'Rewriting for feedburner should happen as \"feeds2.feedburner.com\" -> \"feeds.feedburner.com\"');
INSERT INTO `sanitizing_rules` VALUES (2,1,1,'(?P<unchanged>feedburner\\.com.+)\\?format=xml','\\g<unchanged>',2,'Feedburner URLs should have their \"?format=xml\" query string removed: \r\n\r\nhttp://feeds2.feedburner.com/linuxoutlaws?format=xml \r\nhttp://feeds.feedburner.com/linuxoutlaws \r\n');
INSERT INTO `sanitizing_rules` VALUES (3,1,1,'^\\s+','',0,'Remove leading whitespaces');
INSERT INTO `sanitizing_rules` VALUES (4,1,1,'\\s+$','',0,'Remove trailing whitespaces');
INSERT INTO `sanitizing_rules` VALUES (5,1,1,'^[^(https?):].+','',100,'Empty any string that doesn\'t start with either http or https');
INSERT INTO `sanitizing_rules` VALUES (7,1,0,'(?P<unchanged>feedburner\\.com.+)\\/$','\\g<unchanged>',2,'Feedburner URLs sometimes have a trailing slash, which can be removed safely');
INSERT INTO `sanitizing_rules` VALUES (8,1,1,'^.*[^\\x20-\\x7E].*$', '', 50, 'Remove URLs with non-ascii characters');
INSERT INTO `sanitizing_rules` VALUES (9,1,0,'^http://leoville\\.tv/podcasts/(?P<podcast>\\w+)\\.xml$', 'http://leo.am/podcasts/\\g<podcast>', 10, 'Rewrite URLs of TWiT Podcasts because most users use a URL that is going to break soon (bug 885)');
INSERT INTO `sanitizing_rules` VALUES (10,1,0,'^http://www\\.dancarlin\\.com/dchh\\.xml$', 'http://feeds.feedburner.com/dancarlin/history', 10, 'Rewrite podcast URL of Dan Carlin\'s Hardcore History because the old URL doesn\'t work anymore (bug 855)');
INSERT INTO `sanitizing_rules` VALUES (11,1,1,'^.*\\s.*$', '', 10, 'All URLs that contain spaces are considered invalid');
INSERT INTO `sanitizing_rules` VALUES (12,0,1,'http://media.libsyn.com/media/(?P<res>.*)$', 'http://traffic.libsyn.com/\\g<res>', 10, 'Update new URL for libsy Podcasts (Learn Japanese with Beb and Alex)');
INSERT INTO `sanitizing_rules` VALUES (13,1,0,'^http://site\\.abc\\.go\\.com/abc/xml/podcastRSS\\?(.*&)?feedPublishKey=(?P<key>\\d+)(&.*)?$', 'http://a.abc.com/abc/xml/podcastRSS?feedPublishKey=\\g<key>', 100, 'Merge URLs for ABC Podcasts (bug 977)');
INSERT INTO `sanitizing_rules` VALUES (14,1,1,'^(?P<protocol>[a-zA-Z])://[-_\\w]+(:[^@]+)?@(?P<rest>.+)$', '\\g<protocol>://\\g<rest>', 20, 'Remove HTTP-Authentication from URLs');
INSERT INTO `sanitizing_rules` VALUES (15,0,1,'^(?P<unchanged>http://rpod\\.ru/personal/.+\\.mp[34])\\?[0-9a-z]+$', '\\g<unchanged>', 100, '');
INSERT INTO `sanitizing_rules` VALUES (16,0,1,'^http://\\d+\\.media\\.collegehumor\\.com/(?P<unchanged>.+)$', 'http://1.media.collegehumor.com/\\g<unchanged>', 100, '');
INSERT INTO `sanitizing_rules` VALUES (17,1,0,'(?i)^http://feeds\.feedburner\.com/ShotOfJaq$', 'http://shotofjaq.org/feed/', 100, 'Merges Shot of Jaq feeds to the URL given on their Website');
INSERT INTO `sanitizing_rules` VALUES (18,1,0,'http://shotofjaq\.org/feed$', 'http://shotofjaq.org/feed/', 100, 'Add trailing slash to Shot of Jaq feed URL');
INSERT INTO `sanitizing_rules` VALUES (19,1,0,'(?i)^http://feeds\.feedburner\.com/ShotOfJaqOGG$', 'http://feeds.feedburner.com/ShotOfJaqOgg', 100, 'Unify all Feedburner URLs for the Shot of Jaq Ogg feed (seems it doesn\'t have an shotofjaq.org url)');
INSERT INTO `sanitizing_rules` VALUES (20,1,0,'(?i)^http://feeds\.feedburner\.com/TEDTalks_video$', 'http://feeds.feedburner.com/tedtalks_video', 100, 'Unify all TEDTalks podcasts');
INSERT INTO `sanitizing_rules` VALUES (21,1,0,'(?i)^http://feeds\.feedburner\.com/TEDTalks_audio$', 'http://feeds.feedburner.com/tedtalks_audio', 100, 'Unify all TEDTalks podcasts');
INSERT INTO `sanitizing_rules` VALUES (22,1,0,'(?i)^http://feeds\.feedburner\.com/TedtalksHD$', 'http://feeds.feedburner.com/tedtalkshd', 100, 'Unify all TEDTalks podcasts');
