# Generated by Django 2.2.6 on 2019-12-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_case_insensitive_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
