# Generated by Django 3.2.8 on 2021-10-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_case_insensitive_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="twitter",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
